spring.application.name=taskplanner
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/taskplanner}
spring.datasource.username=${DB_USERNAME:taskplanner_app}
spring.datasource.password=${DB_PASSWORD:change_me}
spring.jpa.hibernate.ddl-auto=update
